version: '3.8'

services:
  web-terminal:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
    volumes:
      - ./data:/app/data
      - gcloud-config:/home/appuser/.config/gcloud
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  gcloud-config:
